spring:
  application:
    name: activityservice
  data:
    mongodb:
      uri: mongodb://mongo:mongo123@localhost:27017/fitness_activity_db?authSource=admin

server:
  port: 8082

management:
  endpoints:
    web:
      exposure:
        include: health, info
  health:
    db:
      enabled: true
    defaults:
      enabled: true
  endpoint:
    health:
      show-details: always
